"""
This script converts CHARMM parameter files (RTF, PRM, PAR) and a PDB structure—
generated by the Multipurpose Atom-Typer for CHARMM (MATCH)—into GROMACS-compatible
topology (.top) and coordinate (.gro) files using ParmEd.

MATCH is a tool for automated atom typing and parameter assignment for small molecules
in the CHARMM force field. The resulting files (RTF, PRM, PAR, and PDB) can be used
for molecular dynamics in CHARMM, but GROMACS requires a different topology format.

This script:
- Loads the MATCH-generated CHARMM parameter and structure files.
- Automatically detects the residue name from the parameter set.
- Ensures all bonds, angles, dihedrals, and impropers are present and unique.
- Builds a complete topology using ParmEd's CHARMM and GROMACS support.
- Outputs GROMACS .top and .gro files for direct use in GROMACS simulations.

Usage example:
    python convertPar2GmxTop.py --pdb cholesterol.pdb --rtf cholesterol.rtf --prm cholesterol.prm --par cholesterol.par

Requirements:
    - ParmEd (with CHARMM and GROMACS support)
    - MATCH-generated CHARMM files (RTF, PRM, PAR, PDB)
"""
from pathlib import Path
import argparse
import parmed as pmd
from parmed import charmm
from parmed.topologyobjects import Angle, Bond, Dihedral, Improper


def convert_charmm_to_gromacs(pdb_path, rtf_path, prm_path, par_path, output_path=None):
    """
    Convert MATCH-generated CHARMM parameter files (RTF, PRM, PAR) and a PDB structure to GROMACS topology and coordinate files.

    Args:
        pdb_path (str or Path): Path to the PDB structure file (from MATCH output).
        rtf_path (str or Path): Path to the CHARMM RTF file (from MATCH output).
        prm_path (str or Path): Path to the CHARMM PRM file (from MATCH output).
        par_path (str or Path): Path to the CHARMM PAR file (from MATCH output).
        output_path (str or Path, optional): Output directory. Defaults to current directory.
    Returns:
        bool: True if conversion is successful.
    """
    pdb_path = Path(pdb_path)
    rtf_path = Path(rtf_path)
    prm_path = Path(prm_path)
    par_path = Path(par_path)
    if output_path is not None:
        output_path = Path(output_path)
    else:
        output_path = Path('.')

    # Load CHARMM parameter set (MATCH output)
    params = charmm.CharmmParameterSet(
        str(rtf_path),
        str(prm_path),
        str(par_path)
    )

    # Automatically extract the first residue name from the parameter set (MATCH usually generates one residue)
    residue_name = next(iter(params.residues.keys()))

    # Load PDB structure (MATCH output)
    struct = pmd.load_file(str(pdb_path))

    # Set all residue names in the structure to match the parameter set
    for residue in struct.residues:
        residue.name = residue_name

    # Get the template residue from the parameter set
    template = params.residues[residue_name]

    # Add missing bonds based on the template (ensure all bonds in the parameter set are present in the structure)
    added_bonds = 0
    for bond in template.bonds:
        atom1 = next((a for a in struct.atoms if a.name == bond.atom1), None)
        atom2 = next((a for a in struct.atoms if a.name == bond.atom2), None)
        if atom1 and atom2:
            bond_exists = any(b for b in struct.bonds if 
                                (b.atom1 == atom1 and b.atom2 == atom2) or
                                (b.atom1 == atom2 and b.atom2 == atom1))
            if not bond_exists:
                struct.bonds.append(pmd.Bond(atom1, atom2))
                added_bonds += 1

    # Build a new CHARMM PSF topology object
    psf = charmm.CharmmPsfFile()

    # Assign atom types from the template residue (required for parameter assignment)
    atom_name_to_type = {a.name: a.type for a in template.atoms}
    for atom in struct.atoms:
        if not getattr(atom, 'type', None) or atom.type == '':
            atom.type = atom_name_to_type.get(atom.name, atom.name)

    # Generate all unique angles
    struct.angles = []
    angle_set = set()
    for atom in struct.atoms:
        bonded = [b.atom2 if b.atom1 == atom else b.atom1 for b in struct.bonds if b.atom1 == atom or b.atom2 == atom]
        for i in range(len(bonded)):
            for j in range(i+1, len(bonded)):
                key = tuple(sorted([bonded[i].idx, atom.idx, bonded[j].idx]))
                if key not in angle_set:
                    struct.angles.append(Angle(bonded[i], atom, bonded[j]))
                    angle_set.add(key)
    # Generate all unique dihedrals
    struct.dihedrals = []
    dihedral_set = set()
    for bond in struct.bonds:
        a1, a2 = bond.atom1, bond.atom2
        a1_neighbors = [b.atom2 for b in struct.bonds if b.atom1 == a1 and b.atom2 != a2] + [b.atom1 for b in struct.bonds if b.atom2 == a1 and b.atom1 != a2]
        a2_neighbors = [b.atom2 for b in struct.bonds if b.atom1 == a2 and b.atom2 != a1] + [b.atom1 for b in struct.bonds if b.atom2 == a2 and b.atom1 != a1]
        for n1 in a1_neighbors:
            for n2 in a2_neighbors:
                key = (n1.idx, a1.idx, a2.idx, n2.idx)
                if key not in dihedral_set:
                    struct.dihedrals.append(Dihedral(n1, a1, a2, n2))
                    dihedral_set.add(key)
    # Generate improper dihedrals from the template (if present)
    struct.impropers = []
    if hasattr(template, 'impropers'):
        for improper in template.impropers:
            atoms = [next((a for a in struct.atoms if a.name == n), None) for n in improper]
            if all(atoms):
                struct.impropers.append(Improper(*atoms))

    # Build the PSF topology from the structure
    for atom in struct.atoms:
        psf.add_atom(
            atom,
            atom.residue.name,
            atom.residue.idx,
            getattr(atom, 'chain', ''),      # chain ID, default to empty string if not present
            getattr(atom.residue, 'insertion_code', ''),  # insertion code, default to empty string if not present
            getattr(atom.residue, 'segid', '')            # segment ID, default to empty string if not present
        )
    # Add all bonds to the PSF
    for bond in struct.bonds:
        idx1 = struct.atoms.index(bond.atom1)
        idx2 = struct.atoms.index(bond.atom2)
        psf.bonds.append(Bond(psf.atoms[idx1], psf.atoms[idx2]))

    # Sync angles, dihedrals, and impropers to the PSF
    psf.angles.extend([a for a in struct.angles])
    psf.dihedrals.extend([d for d in struct.dihedrals])
    if hasattr(struct, 'impropers'):
        psf.impropers.extend([im for im in struct.impropers])

    # Load force field parameters into the PSF
    psf.load_parameters(params)

    # Use the PSF as the final structure for output
    struct_with_params = psf

    # Add coordinates if available
    if struct.coordinates is not None:
        struct_with_params.coordinates = struct.coordinates

    # Print a summary of the final topology
    print(f"Final topology: {len(struct_with_params.atoms)} atoms, {len(struct_with_params.bonds)} bonds, "
          f"{len(struct_with_params.angles)} angles, {len(struct_with_params.dihedrals)} dihedrals")

    # Export to GROMACS .top and .gro files in the output directory
    out_top = output_path / 'cholesterol.top'
    out_gro = output_path / 'cholesterol.gro'
    struct_with_params.save(str(out_top), format='gromacs', overwrite=True)
    struct_with_params.save(str(out_gro), overwrite=True)

    return True

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert MATCH-generated CHARMM files to GROMACS format using ParmEd.")
    parser.add_argument("--pdb", type=str, required=True, help="Path to the PDB structure file (MATCH output)")
    parser.add_argument("--rtf", type=str, required=True, help="Path to the CHARMM RTF file (MATCH output)")
    parser.add_argument("--prm", type=str, required=True, help="Path to the CHARMM PRM file (MATCH output)")
    parser.add_argument("--par", type=str, required=True, help="Path to the CHARMM PAR file (MATCH output)")
    parser.add_argument("--output", type=str, default=None, help="Output directory (default: current directory)")
    args = parser.parse_args()

    convert_charmm_to_gromacs(args.pdb, args.rtf, args.prm, args.par, args.output)